START RequestId: e3fb285f-3f8b-4e46-a88b-49fa90ff608a Version: $LATEST
Hello!
Hmmm, does not add newlines in 3.7?


/usr/bin/python2.7
['/var/runtime/awslambda/bootstrap.py']
/var/task
/var/task/lambda_function.py
{'HOSTNAME': '1b4c405b2132', '_HANDLER': 'lambda_function.lambda_handler', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'LAMBDA_TASK_ROOT': '/var/task', 'HOME': '/home/sbx_user1051', 'PATH': '/usr/local/bin:/usr/bin/:/bin:/opt/bin', 'LD_LIBRARY_PATH': '/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib', 'LANG': 'en_US.UTF-8', 'TZ': ':UTC', 'AWS_REGION': 'us-east-1', 'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR', 'LAMBDA_RUNTIME_DIR': '/var/runtime', 'PYTHONPATH': '/var/runtime', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '1536', '_AWS_XRAY_DAEMON_PORT': '2000', '_AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2', 'AWS_LAMBDA_LOG_GROUP_NAME': '/aws/lambda/test', 'AWS_LAMBDA_LOG_STREAM_NAME': '2019/3/3/[$LATEST]318975d7b6d19bfa', 'AWS_ACCESS_KEY_ID': 'SOME_ACCESS_KEY_ID', '_X_AMZN_TRACE_ID': 'Parent=11560be54abce8ed', 'AWS_DEFAULT_REGION': 'us-east-1', 'AWS_SECRET_ACCESS_KEY': 'SOME_SECRET_ACCESS_KEY', 'AWS_EXECUTION_ENV': 'AWS_Lambda_python2.7', 'AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2:2000', 'AWS_LAMBDA_FUNCTION_NAME': 'test'}
{'aws_request_id': 'e3fb285f-3f8b-4e46-a88b-49fa90ff608a', 'log_stream_name': '2019/3/3/[$LATEST]318975d7b6d19bfa', 'invoked_function_arn': 'arn:aws:lambda:us-east-1:977577338124:function:test', 'client_context': None, 'log_group_name': '/aws/lambda/test', 'function_name': 'test', 'function_version': '$LATEST', 'identity': <__main__.CognitoIdentity object at 0x7f41684b0910>, 'memory_limit_in_mb': '1536'}
END RequestId: e3fb285f-3f8b-4e46-a88b-49fa90ff608a
REPORT RequestId: e3fb285f-3f8b-4e46-a88b-49fa90ff608a Duration: 8 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 14 MB

{"event": {}, "executable": "/usr/bin/python2.7", "context.__dict__": "{'aws_request_id': 'e3fb285f-3f8b-4e46-a88b-49fa90ff608a', 'log_stream_name': '2019/3/3/[$LATEST]318975d7b6d19bfa', 'invoked_function_arn': 'arn:aws:lambda:us-east-1:977577338124:function:test', 'client_context': None, 'log_group_name': '/aws/lambda/test', 'function_name': 'test', 'function_version': '$LATEST', 'identity': <__main__.CognitoIdentity object at 0x7f41684b0910>, 'memory_limit_in_mb': '1536'}", "sys.argv": "['/var/runtime/awslambda/bootstrap.py']", "__file__": "/var/task/lambda_function.py", "ps aux": "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\n496          1  6.0  0.0 207256 15212 ?        Ss   17:20   0:00 /usr/bin/python2.7 /var/runtime/awslambda/bootstrap.py\n496         10  0.0  0.0 117264  2464 ?        R    17:20   0:00 ps aux\n", "os.environ": "{'HOSTNAME': '1b4c405b2132', '_HANDLER': 'lambda_function.lambda_handler', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'LAMBDA_TASK_ROOT': '/var/task', 'HOME': '/home/sbx_user1051', 'PATH': '/usr/local/bin:/usr/bin/:/bin:/opt/bin', 'LD_LIBRARY_PATH': '/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib', 'LANG': 'en_US.UTF-8', 'TZ': ':UTC', 'AWS_REGION': 'us-east-1', 'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR', 'LAMBDA_RUNTIME_DIR': '/var/runtime', 'PYTHONPATH': '/var/runtime', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '1536', '_AWS_XRAY_DAEMON_PORT': '2000', '_AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2', 'AWS_LAMBDA_LOG_GROUP_NAME': '/aws/lambda/test', 'AWS_LAMBDA_LOG_STREAM_NAME': '2019/3/3/[$LATEST]318975d7b6d19bfa', 'AWS_ACCESS_KEY_ID': 'SOME_ACCESS_KEY_ID', '_X_AMZN_TRACE_ID': 'Parent=11560be54abce8ed', 'AWS_DEFAULT_REGION': 'us-east-1', 'AWS_SECRET_ACCESS_KEY': 'SOME_SECRET_ACCESS_KEY', 'AWS_EXECUTION_ENV': 'AWS_Lambda_python2.7', 'AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2:2000', 'AWS_LAMBDA_FUNCTION_NAME': 'test'}", "os.getcwd": "/var/task"}

